hmcts/rd-location-ref-data-load

- charts/rd-location-ref-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-1769
Update chart config
```
[ ] Yes
[X] No
```
> Update chart config

- build.gradle
- src/main/java/uk/gov/hmcts/reform/locationrefdata/Application.java
RDCC-1769
Add app exit code
```
[ ] Yes
[X] No
```
> Adding app exit code

- build.gradle
- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
- charts/rd-location-ref-data-load/values.yaml
- database/Dockerfile
- database/init-db.sh
- docker-compose.yml
- src/main/java/uk/gov/hmcts/reform/locationrefdata/Application.java
- src/main/resources/application.yaml
- src/main/resources/db/migration/V1_1__init_tables.sql
- src/test/java/uk/gov/hmcts/reform/locationrefdata/ApplicationTest.java
https://tools.hmcts.net/jira/browse/RDCC-1868
feat: Create Database of the org urn microservice(RDCC-1868)
No
> feat: Create Database of the org urn microservice(RDCC-1868)

- build.gradle
- infrastructure/main.tf
- infrastructure/state.tf
- infrastructure/terraform.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/RDCC-1911
```
[ ] Yes
[X] No
```
> TF upgrade to 0.12.16 and Azure RM upgrade to 2.20.0 - Master

- src/main/resources/bootstrap.yaml
NA
fix: vault keys in bootstrap.yaml
No
> fix: vault keys in bootstrap.yaml

- infrastructure/main.tf
NA
fix: map vault keys in terra form
No
>  fix: map vault keys in terra form

- src/main/resources/bootstrap.yaml
NA
fix: boot strap prefix enabled
No
> fix: boot strap prefix enabled

- infrastructure/main.tf
- src/main/resources/bootstrap.yaml
NA
fix: boot strap values update
No
> fix: boot strap values update

- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.yaml
NA
fix: key vault config updated
No
> fix: key vault config updated

- build.gradle
NA
fix: removed health check hmcts lib from data-ingestion lib
No
> fix: removed health check hmcts lib from data-ingestion lib

- src/main/resources/bootstrap.yaml
NA
fix: bootstrap values updated
No
> fix: bootstrap values updated

- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
- src/functionalTest/resources/application-integration.yml
- src/main/resources/application-lrd-router.yaml
NA
fix: configuration refactor
No
> fix: configuration refactor

- build.gradle
RDCC-1933
This PR covers the jar bump ups and owasp update
```
[ ] Yes
[X ] No
```
> Bumpsup : Bump ups version and owasp update(RDCC-1933)

- build.gradle
NA
fix: reverting postgres version
No
> fix: reverting postgres version

- Jenkinsfile_nightly
> Fix for failing build

- Jenkinsfile_nightly
> Renamed secret names

- Jenkinsfile_CNP
- build.gradle
- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
- charts/rd-location-ref-data-load/values.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
- src/functionalTest/resources/application-integration.yml
- src/functionalTest/resources/db/testmigration/V1_8__alter_audit_exception_table.sql
- src/main/java/uk/gov/hmcts/reform/locationrefdata/LrdLoadApplication.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/listener/JobResultListener.java
- src/main/resources/application-camel-routes-common.yaml
- src/main/resources/db/migration/V1_8__alter_audit_exception_table.sql
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/listener/JobResultListenerTest.java
https://tools.hmcts.net/jira/browse/RDCC-1927
feat:library updated to check file timestamp of blob and missing blobs(RDCC-1927)
No
> feat:library updated to check file timestamp of blob and missing blobs(RDCC-1927)

- config/owasp/suppressions.xml
feat:nightly build fix by adding suppression
```
[ ] Yes
[X] No
```
> suppressing tomcat ebbed jar

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2011
refactor: updated blob key names
No
> refactor: updated blob key names

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2073
```
[ ] Yes
[X] No
```
> Add sync method call

- src/functionalTest/resources/sourceFiles/service-test.csv
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/ServiceToCcdCaseTypeMapper.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/ServiceToCcdCaseTypeMapperTest.java
RDCC-2102
fix: RDCC-2102 added trimming for file values
```
[ ] Yes
[X] No
```
> RDCC-2102 added trimming for file values

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2143
CVE-2020-8908: Fixing the cve.
```
[ ] Yes
[ ] No
```
> CVE-2020-8908: Fixing the cve.

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2168
increasing bouncycastle:bcpkix-jdk15on to 1.68
```
[ ] Yes
[x] No
```
> RDCC-2168: Fixing Nightly Build

- build.gradle
Update testcontainers dependency version
```
[ ] Yes
[X] No
```
> Update testcontainers version

- Jenkinsfile_CNP
- build.gradle
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
https://tools.hmcts.net/jira/browse/RDCC-2527
fix: add functional test report and suppress camel-2 CVE
No
> fix: add functional test report and suppress camel-2 CVE

- charts/rd-location-ref-data-load/Chart.yaml
NA
fix: updated chart configuration
No
> fix: updated chart configuration

- charts/rd-location-ref-data-load/Chart.yaml
> fix: helm issue

- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
- charts/rd-location-ref-data-load/values.yaml
- src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```
> Update app insights secret key name

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
NA
fix: truncate issue lrd load
No
> fix: truncate issue lrd load

- charts/rd-location-ref-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-2645
```
[ ] Yes
[X] No
```
> Update job chart version

- build.gradle
NA
CVE-2021-21409: Fixing the cve.
```
[ ] Yes
[x] No
```
> CVE-2021-21409: Fixing the cve.

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2682
refactor: Used data-ingestion library published in JIT Pack
No
> refactor: Used data-ingestion library published in JIT Pack

- Jenkinsfile_nightly
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-2900
Nightly build missing security scan step and reports added
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
> RDCC-2900 Nightly jenkins script changes done to enable security scan

- Jenkinsfile_nightly
- audit.json
- security.sh
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2960
Fixed security scan reported issue
```
[ ] Yes
[x] No
```
> fix: RDCC-2960 Added missing security.sh file

- Jenkinsfile_CNP
- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
https://tools.hmcts.net/jira/browse/RDCC-2331
refactor: Aks Blob chart with functional test cases
```
[ ] Yes
[X] No
```
> refactor: Aks Blob chart with functional test cases

- audit.json
- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.yaml
NA
fix: corrected yaml configuration aat
```
[ ] Yes
[X] No
```
> fix: corrected yaml configuration aat

- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
- charts/rd-location-ref-data-load/values.yaml
- src/main/resources/bootstrap.yaml
Removed unwanted secret variable
```
[ ] Yes
[X] No
```
> Removed unwanted secret variable

- security.sh
> chnage order of commands to fix security scan

- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
- src/functionalTest/resources/db/testmigration/V1_12__building_location_test_insert.sql
- src/functionalTest/resources/testData/insert-building-location.sql
- src/functionalTest/resources/testData/truncate-lrd-court-venue.sql
https://tools.hmcts.net/jira/browse/RDCC-2985
Added new test sql script and removed previous flyway insert script
```
[ ] Yes
[x] No
```
> RDCC-2985_2: functional test build fix

- Jenkinsfile_nightly
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
Nightly build failure investigation
```
[ ] Yes
[X] No
```
> Nightly failure investigation - removed mutation step

- Jenkinsfile_nightly
Enabling mutation tests in the nightly build
```
[ ] Yes
[x] No
```
> enabled mutation tests in the nightly job

- Jenkinsfile_nightly
> RDCC-3159: Changed the nightly build schedule to 14:00 BST

- Jenkinsfile_nightly
> RDCC-3159: Changed the nightly build schedule to 15:00 BST

- Jenkinsfile_nightly
> RDCC-3159: Changed the nightly build schedule to 15:30

- Jenkinsfile_nightly
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
> RDCC-3159: Changed the nightly build schedule to 18:15 UTC

- Jenkinsfile_nightly
> RDCC-3159: Changed the nightly build schedule to 01:21 UTC.

- charts/rd-location-ref-data-load/Chart.yaml
- infrastructure/terraform.tf
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-3290
- Upgraded the job chart version to latest
- used fixed version of azuread 
Does this PR introduce a breaking change? (check one with "x")
```
[ ] Yes
[x] No
```
> feat: RDCC-3290 Upgraded job chart version and used fixed version of azuread 

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/config/LrdCamelConfig.java
- src/functionalTest/resources/application-integration.yml
- src/functionalTest/resources/db/testmigration/V1_12__alter_dataload_exception_records_add_row_id.sql
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocation.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/ServiceToCcdCaseType.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/IClusterRegionProcessor.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
- src/main/resources/application-camel-routes-common.yaml
- src/main/resources/db/migration/V1_12__alter_dataload_exception_records_add_row_id.sql
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-3230
Added RowID to the exception table and populated data into it
```
[ ] Yes
[x] No
```
> feat: RDCC-3230 Added RowID to the exception table and populated data into it

- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
- src/functionalTest/resources/application-integration.yml
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-failure-columns-in-jumbled-order.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-failure.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-partial-success.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-cluster.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-court-type-id.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-epimms-id.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test-partial-success-non-existent-region.csv
- src/functionalTest/resources/sourceFiles/courtVenues/court-venue-test.csv
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenue.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapper.java
- src/main/resources/application-lrd-court-venue-router.yaml
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenueTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapperTest.java
https://tools.hmcts.net/jira/browse/RDCC-3485
Added changes to camel ingestion for the court venue file
```
[ ] Yes
[x] No
```
> RDCC-3485: Changes to Camel ingestion for Court Venue file

- build.gradle
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-3557
Upgraded spring core version to fix CVE-2021-22096
```
[ ] Yes
[x] No
```
> fix: RDCC-3557 Upgraded spring core version to fix CVE-2021-22096

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
- src/smokeTest/java/uk/gov/hmcts/reform/locationrefdata/SmokeTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/BuildingLocationTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/CourtVenueTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/binder/ServiceToCcdCaseTypeTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/BuildingLocationMapperTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/CourtVenueMapperTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/mapper/ServiceToCcdCaseTypeMapperTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessorTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessorTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessorTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdBuildingLocationRouteTaskTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/task/LrdCourtVenueRouteTaskTest.java
- src/test/java/uk/gov/hmcts/reform/locationrefdata/camel/util/LrdLoadUtilsTest.java
https://tools.hmcts.net/jira/browse/RDCC-3520
Migrated unit, smoke and functional tests to Junit5
```
[ ] Yes
[x] No
```
> RDCC-3520: LRD JUnit 4 to JUnit 5 migration

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3681
Publish Jenkins Tests Report
```
[ ] Yes
[X] No
```
> Publish Jenkins Tests Report

- .dependabot/config.yml
- .github/dependabot.yml
- build.gradle
Changes made to fix bot PRs
```
[ ] Yes
[ x] No
```
> Feat:Changes made to fix bot PRs

- build.gradle
Changes made to fix new bot pr issues resolution
```
[ ] Yes
[ x] No
```
> Feat:Changes made to fix bot pr issues

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3903
Revert the tomcat version to previous version
```
[ ] Yes
[x] No
```
> fix: RDCC-3903 Revert the tomcat version to previous version

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDCC-3840
Enabled fortify scan
```
[ ] Yes
[x] No
```
> fix: RDCC-3840 Enabled fortify scan

- build.gradle
- config/owasp/suppressions.xml
> added fix with latest spring version

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationsLoadTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
https://tools.hmcts.net/jira/browse/RDCC-3923
Removed deprecated jcenter repository
```
[ ] Yes
[x] No
```
> RDCC-3923: LRD-data-load Remove Deprecated Jcenter Repository

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-4048
Fixed CVEs
```
[ ] Yes
[x] No
```
> RDCC-4048: Fix CVEs

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Gradle Upgrade 7.3.3
```
[ ] Yes
[X ] No
```
> Rdcc gradle upgrade

- src/main/java/uk/gov/hmcts/reform/locationrefdata/LrdLoadApplication.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/listener/JobResultListener.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/BuildingLocationProcessor.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/CourtVenueProcessor.java
- src/main/java/uk/gov/hmcts/reform/locationrefdata/camel/processor/ServiceToCcdCaseTypeProcessor.java
https://tools.hmcts.net/jira/browse/RDCC-4032
https://tools.hmcts.net/jira/browse/RDCC-4032
```
[ ] Yes
[x] No
```
> added logging and improvisation

- build.gradle
> LRD : fix CVE-2020-36518

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4331
```
[ ] Yes
[X] No
```
> RDCC-4331 updated for CVE 2020-36518

- build.gradle
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-4402
CVE Fix
```
[ ] Yes
[x] No
```
> RDCC-4402: CVE Fix

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4427
```
[ ] Yes
[X] No
```
> updated for CVe Fixes

- Dockerfile
- build.gradle
- docker-compose.yml
https://tools.hmcts.net/jira/browse/RDCC-4354
Java 17 Migration for Location Reference Data
```
[ ] Yes
[X] No
```
> JDK17 upgrade changes

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4699
CVE fix for Tomcat embed
```
[ ] Yes
[x] No
```
> RDCC-4699: CVE fix for tomcat embed

- Dockerfile
- acb.tpl.yaml
- build.gradle
> Ref data - LRD load Add multi arch image configuration

- renovate.json
https://tools.hmcts.net/jira/browse/RDCC-4816
Configured renovate
```
[ ] Yes
[x] No
```
> config: RDCC-4816 Configured renovate

- charts/rd-location-ref-data-load/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5005
Updated service bus chart version to latest
```
[ ] Yes
[x] No
```
> RDCC-5005: Update the chart version of service bus and blob storage to the latest

- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDCC-5064
upgraded bitnami chart version
```
[ ] Yes
[x] No
```
> RDCC-5064: upgraded bitnami chart version

- config/owasp/suppressions.xml
> RDCC-5392: adding suppression for CVE-2022-25857

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5534
Upgrading `snakeyaml` to fix CVE-2022-38752
```
[ ] Yes
[x] No
```
> RDCC-5534: Upgrading `snakeyaml`

- src/main/resources/db/migration/V1_23__create_views.sql
Create Views
```
[ ] Yes
[X] No
```
> views creation

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/RDCC-5931
```
[ ] Yes
[X] No
```
> Replace after with afterSuccess for depreciated : RDCC-5931

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationExceptionAndAuditTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdApplicationTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdBuildingLocationFileStatusCheck.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdCourtVenueTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/LrdFileStatusCheckTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdBlobSupport.java
- src/functionalTest/resources/application-integration.yml
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-6180
[RDCC-6180]Spring Boot upgrade - Dataload project (Location Reference Data)
```
[ ] Yes
[ x] No
```
> [RDCC-6180]Spring Boot upgrade - Location Reference Dataload project

- build.gradle
- charts/rd-location-ref-data-load/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6244
Upgrade OWASP security libs in data ingestion
```
[ ] Yes
[ x] No
```
> [RDCC-6244]- OWASP upgrade for Location ref data load

- Jenkinsfile_CNP
Changing slack notification channel 
```
[ ] Yes
[X] No
```
> changing slack notification channel for pr build updates

- src/main/resources/application-lrd-building-location-router.yaml
- src/main/resources/application-lrd-court-venue-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-6437
[RDCC-6437] Fix of header validation for Court-venue and building location files
```
[ ] Yes
[ x] No
```
> [RDCC-6437] Fix of header validation for Court-venue and building location files

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6427
Address CVEs in all Reference Data repositories - Location Reference Data
```
[ ] Yes
[ x] No
```
> Feat:Address CVEs in all Reference Data repositories - Location Reference Data

- charts/rd-location-ref-data-load/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6611
Suppress https://github.com/advisories/GHSA-mjmj-j48q-9wg2
```
[ ] Yes
[x] No
```
> RDCC-6611: suppress CVE-2022-1471

- config/owasp/suppressions.xml
addresses CVE-2023-20859
https://tools.hmcts.net/jira/browse/RDCC-6676
addresses CVE-2023-20859
```
[ ] Yes
[x] No
```
> Nightly build failure

- Jenkinsfile_CNP
- charts/rd-location-ref-data-load/Chart.yaml
- charts/rd-location-ref-data-load/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/DTSRD-148
Added suffix for blob storage according to:
https://github.com/hmcts/chart-blobstorage#migration-to-v10-from-osba-to-aso
```
[ ] Yes
[x] No
```
> added -blobstorage suffix

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-327
Applied remedy from https://spring.io/security/cve-2021-22044
```
[ ] Yes
[x] No
```
> Addresses CVE-2021-22044

- charts/rd-location-ref-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSRD-457
Upgrade chart-job to v 1.0.0
```
[ ] Yes
[x] No
```
> Upgrade chart-job to v 1.0.0

- src/functionalTest/java/uk/gov/hmcts/reform/locationrefdata/cameltest/testsupport/LrdIntegrationBaseTest.java
https://tools.hmcts.net/jira/browse/RDCC-6746
[RDCC 6746]-upgrade deprecated methods to java 17
```
[ ] Yes
[ x] No
```
> [RDCC 6746]-upgrade deprecated methods to java 17

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-793
Suppress CVE-2023-34442 while I work on the actual fix
```
[ ] Yes
[x] No
```
> Suppress CVE-2023-34442 - working on fix

- build.gradle
- config/owasp/suppressions.xml
> CVE: Address CVE-2023-34034 

- config/owasp/suppressions.xml
> CVE-2023-34047

- config/owasp/suppressions.xml
> Update suppressions.xml to fix CVE-2023-4759

- config/owasp/suppressions.xml
Suppresses CVE-2023-36052 (a likely false positive)
```
[ ] Yes
[x] No
```
> CVE-2023-36052 suppression

- build.gradle
Remedies CVE-2023-35887
```
[ ] Yes
[x] No
```
> Addresses CVE-2023-35887

- config/owasp/suppressions.xml
> suppress CVE-2023-48795

- charts/rd-location-ref-data-load/Chart.yaml
> update chart job version

- build.gradle
- charts/rd-location-ref-data-load/Chart.yaml
Addresses CVE-2023-34042
```
[ ] Yes
[x] No
```
> Addresses CVE-2023-34042

- infrastructure/terraform.tf
> Fix Provider issues

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-3025
```
[ ] Yes
[ ] No
```
> Removed deprecated dependency

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- Jenkinsfile_template
- charts/rd-location-ref-data-load/Chart.yaml
- src/main/resources/testcontainers.properties
https://tools.hmcts.net/jira/browse/DTSRD-3041
Image registry prefix for testcontainers
```
[ ] Yes
[ ] No
```
> Dtsrd 3041

- build.gradle
> Update build.gradle. fixing nightly build

- Jenkinsfile_CNP
- charts/rd-location-ref-data-load/values.preview.template.yaml
- src/functionalTest/resources/application-integration.yml
- src/functionalTest/resources/db/testmigration/V1_27__alter_table_court_venue_constraints.sql
- src/main/resources/application-lrd-court-venue-router.yaml
> DTSRD-3066: CHG5017234 - Location data - Amend the unique key in court

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-3685
CVE-2024-38820 Suppression
```
[ ] Yes
[ ] No
```
> DTSRD-3685 CVE-2024-38820 Suppression

- build.gradle
DTSRD-3710 Reverts hmcts/rd-location-ref-data-load#531
> DTSRD-3710 Revert "Update dependency org.pitest:pitest to v1.17.1"

- infrastructure/terraform.tf
Update azurerm to 4.10
```
[ ] Yes
[x] No
```
> Addresses master build failure

- build.gradle
> DTSRD-3404: Fix aat deployment issue

- infrastructure/terraform.tf
Update azurerm to 3.106
```
[ ] Yes
[x] No
```
> Restore azurerm 3.106

- build.gradle
Reverts renovate upgrade to 3.4.0
```
[ ] Yes
[x] No
```
> spring-boot 3.3.5

- charts/rd-location-ref-data-load/Chart.yaml
Chart version bump
```
[ ] Yes
[x] No
```
> Update Chart to 0.0.34

- build.gradle
Update data-ingestion-lib to released 0.6.0.0
```
[ ] Yes
[x] No
```
> data-ingestion-lib upgrade

- infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/CME-298
```
[ ] Yes
[x ] No
```
> CME-298: Update azurerm

- build.gradle
Removed newline at end to kick off build
```
[ ] Yes
[x] No
```
> Kick off master build to re-enable on Jenkins

- charts/rd-location-ref-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-408
```
[ ] Yes
[ x] No
```
> CME-408: Update OCI endpoint

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-4788
Update data-ingestion-lib to 0.6.0.4_beta
```
[ ] Yes
[x] No
```
> DTSRD-4788
